### ISSUE TITLE
Info requested

### ISSUE THREAD

**Issue by borisdifiore** [nabble/semalt-blocker#22]
Hi all,
I would like to ask if any manual is available to set up your script in an hosted site.
Actually I use the scripts manually uploading to .htaccess (my site is hosted on dreamhost with apache engine)
Actually my .htaccess is growing tooooooo much and speed down my site (e-commerce site)
Thank you in advance
Boris

**Comment by hongaar** [comment]
Do you use the `blocked.conf` file? I don't actually test performance impact of using this .htaccess/apache configuration, any chance you can provide some kind measurement for this? I.e. the performance impact of the PHP blocker is +- .5ms, and I'm curious to know what the impact of having 2000+ rules in a .htaccess file has on requests.
