### ISSUE TITLE
Add own referer

### ISSUE THREAD

**Issue by Creat1veM1nd** [nabble/semalt-blocker#23]
Hello,

so far, your scripts work without problem! Thanks for coding it!

I do have a question though: is it possible to provide a file which contains additional referer for blocking and which is not overwritten by autoupdate ? 

Thanks!

Dragon013

**Comment by hongaar** [comment]
I think it'd be best if the Blocklist would be abstracted away in its own class. Right now this is simply handled by calling `file_get_contents` in the [Blocker class](https://github.com/nabble/semalt-blocker/blob/master/src/SemaltBlocker/Blocker.php#L240). Feel free to submit a PR, I will also see if I can make time for this in the near future (and fix the Travis errors).

**Comment by thedragon013** [comment]
Sadly I am not familiar with how to work with GitHub, so I would like to note down my changes right here. It's quick and dirty, but so far, it works.

Right on the beginning I added: 
`private static $ownBlocklist = './../../domains/ownBlocked';`

Above the method for getting the Blocklist (getBlocklistFilename) I added:
` /**
     * @return string
     */
    public static function getOwnBlocklistFilename()
    {
        return __DIR__ . DIRECTORY_SEPARATOR . static::$ownBlocklist;
    }`

The method for reading the blocklist (getBlocklistContents) I replaced with: 
` /**
     * @return string
     */
    private static function getBlocklistContents()
    {
        $blocklistContent = file_get_contents(self::getBlocklistFilename());
		if(file_exists(self::getOwnBlocklistFilename()))
		{
		$blocklistContent.=file_get_contents(self::getOwnBlocklistFilename());
		}
        return $blocklistContent;
    }`
