### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by romather** [nabble/semalt-blocker#28]
Using composer have a following error:

[screenshot_39](https://user-images.githubusercontent.com/47756883/53827431-d5049f80-3f59-11e9-8afb-c51d38896780.png)

**Comment by romather** [comment]
Install through composer have following error:

![screenshot_39](https://user-images.githubusercontent.com/47756883/53827487-f8c7e580-3f59-11e9-8407-c25bb2420835.png)

**Comment by hongaar** [comment]
Unfortunately, semalt-blocker was pulled from packagist due to a complaint from semalt (big surprise).

You could add the followin to `composer.json`:

```
"repositories": [
  {
    "type": "vcs",
    "url": "https://github.com/nabble/semalt-blocker"
  }
],
```
