### ISSUE TITLE
Non-coder instructions & integration with WordPress

### ISSUE THREAD

**Issue by tylerregas** [nabble/semalt-blocker#6]
It would be a huge help if you could write up instructions for people who are not programmers so that we might use your code in WordPress installations. Just a little bit about where best to place the code and how it works from the standpoint of a layperson :) Thanks! -TC

**Comment by hongaar** [comment]
I think the best and easiest way to use this library in a WP install is through a plugin, as this will (hopefully) keep the blacklist updated for you.

To use this library in WP without using a plugin, I'd recommend copying both `domains/blocked` and `compact/semaltblocker.php` to a new directory `[TEMPLATEDIR]/semalt-blocker` and then adding these lines to your `functions.php`:

```
require "semalt-blocker/semaltblocker.php";
\Nabble\Semalt::block();
```

But please keep in mind this library is intentionally written for programmers, and the above method of editing your `functions.php` should only be used if you're comfortable with editing and maintaining code.
